services:
  backend:
    container_name: backend
    build: .
    env_file:
      - .env
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: ./main.py
      FLASK_ENV: development
    depends_on:
      - db
  db:
    container_name: database
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./migrations/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
  adminer:
    image: adminer
    restart: always
    ports:
      - "8282:8080"
    depends_on:
      - db
volumes:
  postgres-data: