version: '3.8'
name: finance-app

services:

  adonis_app:
    container_name: adonis_app
    restart: always
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${PORT}:${PORT}
      - 9229:9229
    env_file:
      - .env
    environment:
      - PG_HOST=${DB_HOST}
    volumes:
      - ./:/home/node/app
    command: dumb-init node ace serve --watch --node-args="--inspect=0.0.0.0"

  db: 
    image: postgres:10-alpine
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
  admin:
    image: adminer
    restart: always
    depends_on: 
      - db
    ports:
      - 8080:8080
    

volumes:
  postgres_volume:
