version: '3.8'
name: finance-app

services:
  adonis_app:
    container_name: adonis_app
    restart: always
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${PORT}:${PORT}
      - 9229:9229
    env_file:
      - .env
    environment:
      - PG_HOST=${DB_HOST}
    volumes:
      - ./:/home/node/app
      - node_modules:/home/node/app/node_modules
    command: dumb-init npm run start
    networks:
      - finance_network

  db:
    image: postgres:10-alpine
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    networks:
      - finance_network

  admin:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080
    networks:
      - finance_network

networks:
  finance_network:

volumes:
  postgres_volume:
  node_modules:

